### ISSUE TITLE
make test doesn't work

### ISSUE THREAD

**Issue by bigfatbird** [Kiyoshika/gosub-client-macos#21]
While trying out compiling the macOS client on my machine building the libs and bindings correctly didn't work

Some errors were found while running 

```
make test
```
in gosub-engine/gosub-bindings

<img width="682" alt="Screenshot 2023-11-27 at 16 01 34" src="https://github.com/gosub-browser/gosub-client-macos/assets/1159341/05f53acc-ce5d-4407-92b6-75a8bf0af26c">

**Comment by Kiyoshika** [comment]
can you also paste the output of “gcc -v” (should be an alias to apple clang on macs)

**Comment by bigfatbird** [comment]
```
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Kiyoshika** [comment]
You said you are on silicon now? (But previously intel)

**Comment by bigfatbird** [comment]
Yes. Bought the Mac in 2022 and migrated from an Intel with Migration Assistant.

**Comment by Kiyoshika** [comment]
Hmm, so when you migrated did it also migrate your rust compiler? I wonder if completely reinstalling rust/rustup will help

**Comment by bigfatbird** [comment]
I only added rust recently via rustup

**Comment by Sharktheone** [comment]
I've heard somewhere, that the apple terminal sometimes runs via rosetta. So probably you need to disable it and then your termial runs with arm64 and not with x86_64.

**Comment by bigfatbird** [comment]
LOL, wtf... will try tomorrow.

**Comment by Kiyoshika** [comment]
yeah, that's odd. I have two macbooks but they are the same arch (arm64) so I can't test one with intel...

honestly I'm not sure what to do at this point lol, it seems to work for both of my laptops and Shark/Eric (both on Linux). Something odd must've happened with the migration

**Comment by Sharktheone** [comment]
Found it... Maybe it helps for figuring out, what to do. modularml/mojo#1078. It's for another repository, but the steps should probably be the same.

**Comment by bigfatbird** [comment]
Jeez... Thanks for the hint, I will try to reinstall homebrew... in hope of not fucking up any of my other workflows...

**Comment by Kiyoshika** [comment]
Just curious, did you ever get this to work?

**Comment by bigfatbird** [comment]
I will try tomorrow

**Comment by Kiyoshika** [comment]
ok, the process has also been simplified as of this morning. You should now only have to clone this repo (with `--recurse-submodules`) and run `make`. You won't need to build/copy anything yourself anymore

**Comment by bigfatbird** [comment]
It works now.

Somehow my rust-compiler was not migrated from intel to apple silicon...
